docs: change the file name to 'create-ssl.py'.If 'ssl.py' is used as the file name, an error occurs.AttributeError: module 'requests' has no attribute 'put'